spring:
  application:
    name: flash-accommodation-booking

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080

resilience4j:
  retry:
    instances:
      pg-api:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - com.flashaccommodationbooking.global.exception.PgNetworkException
        ignore-exceptions:
          - com.flashaccommodationbooking.global.exception.BusinessException
  circuit-breaker:
    instances:
      pg-api:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        ignore-exceptions:
          - com.flashaccommodationbooking.global.exception.BusinessException
      redis:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        ignore-exceptions:
          - com.flashaccommodationbooking.global.exception.BusinessException
